export default {
  timeout: 'timeout of',
  networkerror: 'Network Error',
  production: 'production',
  dev: 'dev',
  sbr: 'SBR',
  sbnsharia: 'SBN_SYARIAH',
  st: 'ST',
  sr: 'SR',
  ori: 'ORI',
  isNumZero: 0,
  isNumOne: 1,
  available: 'available',
  pending: 'pending',
  unavailable: 'unavailable',
  isNumSharia: 2,
  isStrOne: '1',
  statusVerified: 'verified',
  statusUnverified: 'unverified',
  statusWaitVerified: 'waiting',
  isNumConven: 1,
  isNumConvenSharia: 3,
};
